// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var initialState = {
  counter: 0
};

function resolveOption(option) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  } else {
    return initialState;
  }
}

function counter(state, action) {
  if (Caml_obj.caml_equal(state, undefined)) {
    return initialState;
  } else {
    var match = action.tag;
    switch (match) {
      case 0 : 
          return {
                  counter: state.counter + 1 | 0
                };
      case 1 : 
          return {
                  counter: state.counter - 1 | 0
                };
      case 2 : 
          return state;
      
    }
  }
}

exports.initialState = initialState;
exports.resolveOption = resolveOption;
exports.counter = counter;
/* No side effect */
