// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReactRedux = require("react-redux");
var App$ReactHooksTemplate = require("./App.bs.js");
var Store$ReactHooksTemplate = require("./Store.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(ReactRedux.Provider, {
          store: Store$ReactHooksTemplate.store,
          children: React.createElement(App$ReactHooksTemplate.make, { })
        }), "index");

/*  Not a pure module */
