// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Redux = require("redux");
var ReactRedux = require("react-redux");
var ReduxDevtoolsExtension = require("redux-devtools-extension");
var CounterReducer$ReactHooksTemplate = require("./reducers/CounterReducer.bs.js");

var store = Redux.createStore(Redux.combineReducers({
          counter: CounterReducer$ReactHooksTemplate.counter
        }), ReduxDevtoolsExtension.composeWithDevTools(ReactRedux.applyMiddleware()));

exports.store = store;
/* store Not a pure module */
